### ISSUE TITLE
Migrate issues, projects and labels?

### ISSUE THREAD

**Issue by Thesola10** [Artemis-chan/osu-DIVA#12]
I have archived my fork, [thesola10/osu-DIVA](https://github.com/thesola10/osu-DIVA) in an effort to preserve the information contained. This is just an inquiry on whether we should copy issues and projects over from there.

**Comment by Artemis-chan** [comment]
dont need, i'll mention issues directly from your fork. and i'll update them as needed

**Comment by Artemis-chan** [comment]
you don't need to archive the repo

**Comment by Thesola10** [comment]
I could pull your changes to "my" repo then switch ownership over it to you, that would solve the problem i think

**Comment by Artemis-chan** [comment]
ah no, you can archive your repo, i will manually transfer the issues down the line

**Comment by Artemis-chan** [comment]
ahh im lazy i dont think ill do it
