### ISSUE TITLE
arrows don't presses

### ISSUE THREAD

**Issue by ChervyachokMigo** [Artemis-chan/osu-DIVA#120]
i can't play because bug: arrow notes hit only if i press arrow key on keyboard together with direction of remapped key.
i need to press arrow note "D" and "right direction key" toogether to hit "great"

Also i can remap all notes to one key  then some notes been hit "great" and some notes "miss"
![image](https://user-images.githubusercontent.com/74270643/212569013-03522d9b-7ceb-4c1d-9953-82ca0dfa364f.png)

**Comment by Artemis-chan** [comment]
I am not sure what you mean by the first issue. In original diva you have to press both buttons to activate the arrow notes. So that's intended as well.

The second is thing is also intended, and manged by lazer nothing to with this mod.

**Comment by Thesola10** [comment]
The labels on the keys are kind of confusing -- Left, Up, Right and Down refer to the corresponding buttons on a PlayStation controller, and just like in Diva F and F 2nd, the arrow _icons_ in gameplay require pressing both the action button and the arrow button in the same direction.

**Comment by ChervyachokMigo** [comment]
ok i understood
