### ISSUE TITLE
Game Crashes When a Note Appears

### ISSUE THREAD

**Issue by YaoiYuriChan** [Artemis-chan/osu-DIVA#145]
When the first note reaches the judgement area, the game crashes

## Version
2024.130.2-Lazer
https://github.com/Artemis-chan/osu-DIVA/actions/runs/7525729543
Mac

## Logs
[1706644865.network.log](https://github.com/Artemis-chan/osu-DIVA/files/14103552/1706644865.network.log)
[1706644865.performance.log](https://github.com/Artemis-chan/osu-DIVA/files/14103553/1706644865.performance.log)
[1706644865.runtime.log](https://github.com/Artemis-chan/osu-DIVA/files/14103554/1706644865.runtime.log)

## Notes
I think it had been like this for several versions before, up to several months before

**Comment by Artemis-chan** [comment]
Hey, thanks for the detailed issue.
There were breaking changes recently, but I tested it working fine a couple of weeks ago.
Please try [this](https://github.com/Artemis-chan/osu-DIVA/actions/runs/7739874158) on 2024.131.0-lazer.

**Comment by OfficialCRUGG** [comment]
@Artemis-chan The file on the link you sent has expired. Any way we could get an updated version that runs on current lazer?

**Comment by Artemis-chan** [comment]
For future reference, please follow the instructions [here](https://github.com/Artemis-chan/osu-DIVA#installation) to download the build from [Actions](https://github.com/Artemis-chan/osu-DIVA/actions?query=workflow%3Adotnet-debug+is%3Asuccess)
