### ISSUE TITLE
My game cant add this rule set release

### ISSUE THREAD

**Issue by yarik303** [Artemis-chan/osu-DIVA#19]
![image](https://user-images.githubusercontent.com/75032600/123227322-25aeb680-d4dd-11eb-8027-cc34d7f2987b.png)

**Comment by Artemis-chan** [comment]
what's version of your lazer?

**Comment by yarik303** [comment]
2021.623.0

**Comment by yarik303** [comment]
same thing with compiling version

**Comment by Artemis-chan** [comment]
just bumped to latest version

**Comment by Artemis-chan** [comment]
tested, it works now
