### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Akuna0** [Artemis-chan/osu-DIVA#23]
so i binded the keys used for the gameplay to buttons on a ps4 controller. the core shapes (circle, Triangle, Square, and X) are all fine but when i see the arrows i dont know what to press. Please help!

**Comment by Artemis-chan** [comment]
Bind the D-pad with `left`, `right`, `up`, `down` buttons. And press buttons in the direction of the arrow in both d-pad and face buttons at once. (i.e. see Up-arrow: press `Triangle` and `Up on d-pad` at once)

**Comment by Akuna0** [comment]
Ok thank you, I've only every played project diva Mega39's so I didn't know what those mechanics were.

**Comment by Thesola10** [comment]
The mechanics were my suggestion, based on F and F2nd gameplay

**Comment by Artemis-chan** [comment]
it's all good then i guess
