### ISSUE TITLE
Skin/hitnotes?

### ISSUE THREAD

**Issue by Akuna0** [Artemis-chan/osu-DIVA#24]
so when im in the game all the notes and symbols are pixelated and in a youtube video i saw it had the proper project diva symbols. Is there a special skin i need to download from somewhere? 
![osu_2021-07-17_11-13-50](https://user-images.githubusercontent.com/87554276/126046160-03dc53ad-a5a0-4477-a9ed-d79c7886ca60.jpg)

**Comment by Thesola10** [comment]
This is the current state of the default icons I'm afraid. I don't know where you saw a video with proper symbols but that must have been from either the old osu!stable ruleset of the same name (not affiliated) or the original Project DIVA games which are unrelated to osu! or this project.

**Comment by Artemis-chan** [comment]
yeah, i just made some pixel art placeholders, it is planned to get something similar to the original project diva tho.

**Comment by Artemis-chan** [comment]
btw where can you link the youtube video @Akuna0

**Comment by Akuna0** [comment]
https://www.youtube.com/watch?v=0W5VgrWbBNM&t=34s theres the video. I dont know if they added some sort of extension to your mod or what but this video is what introduced me to the project diva mod on osu!. ive played project diva games is the past.

**Comment by Thesola10** [comment]
Indeed it seems they skinned the button icons. They're skinnable like any other osu! elements.

**Comment by Artemis-chan** [comment]
yeah they look like they're from future tone(or probably also some other). must be skinned or recompiled with the buttons

**Comment by Artemis-chan** [comment]
oh yeah they did say in description that they've changed the sprites and sounds

**Comment by Artemis-chan** [comment]
ok, it's done(a5c71e3aa86f6e0da3e46af1d02c873d5c3ef07c). good enough for now >w<
