### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by 4zjata** [Artemis-chan/osu-DIVA#3]
When you gonna publish release, I really wanna try this out. Or can you make compile instructions?

**Comment by PoltixeTheDerg** [comment]
Its compilable the same way as any other dotnet project, instructions for any other project should work here

**Comment by Artemis-chan** [comment]
So I bumped the version of base repo and published a pre-release version. Also made a small instruction on compilation and installation. Hope they are okay. (omitted the installation in osu installation directory cus that changes through os, for now at least)
