### ISSUE TITLE
Failed to add ruleset

### ISSUE THREAD

**Issue by Knodera** [Artemis-chan/osu-DIVA#38]
When I copy the ruleset into the rulesets folder the game gives and error saying "Failed to add ruleset osu.game.Rulesets.Diva, Version 1.0.0.0, Culture=neutral, PublicKeyToken=null". I am running version 2021.927.0-lazer
![osu! Screenshot 2021 10 02 - 13 52 54 81](https://user-images.githubusercontent.com/85378694/135727083-382ea1cd-f3ca-4ea9-bbc8-ca9f0b259367.png)
.

**Comment by Thesola10** [comment]
osu!lazer is a rapidly moving target, and we have CI tasks to automatically bring up the most obvious build issues. If the automated build for this version was successful, we may need additional logs to look into the issue.

**Comment by Thesola10** [comment]
Otherwise, try building the ruleset from source code, maybe the prebuilt releases are lagging behind.

**Comment by Knodera** [comment]
I will try building it now. What logs would you need to look into it?

**Comment by Knodera** [comment]
I built the ruleset and it works from there. Thanks for the help!

**Comment by starisstupid** [comment]
> Otherwise, try building the ruleset from source code, maybe the prebuilt releases are lagging behind.
