### ISSUE TITLE
How to build ruleset?

### ISSUE THREAD

**Issue by starisstupid** [Artemis-chan/osu-DIVA#43]
> Otherwise, try building the ruleset from source code, maybe the prebuilt releases are lagging behind.

*Originally posted by @Thesola10 in https://github.com/Artemis-chan/osu-DIVA/issues/38#issuecomment-932796518_*

Im having the same issue,i followed what you said there
but im still confused on how to build the ruleset from source code,
maybe can you show me how?

**Comment by Artemis-chan** [comment]
you can follow this https://github.com/Artemis-chan/osu-DIVA#compilation

**Comment by starisstupid** [comment]
I followed the steps,and it worked,thanks!
