### ISSUE TITLE
"An unhandled error has occured." While loading a Beatmap.

### ISSUE THREAD

**Issue by GiraffeMan3125** [Artemis-chan/osu-DIVA#5]
Anytime I try to load a beat map on this mode, I get the "An unhandled error has occurred." notification. I have attached a .log file. (macOS Big Sur 11.0.1)
[runtime.log](https://github.com/Artemis-chan/osu-DIVA/files/5639593/runtime.log)

(No controller was connected when this log was uploaded, let me know if you need a log with the Controller connected)

**Comment by Artemis-chan** [comment]
the newer versions of lazer isn't supported yet.
I'll update it later. Also I need to add a proper beatmap conversion.

**Comment by GiraffeMan3125** [comment]
I'll play on an older version for now.

**Comment by Thesola10** [comment]
I did the update thing! #6
