### ISSUE TITLE
Ruleset fails to add after 2022.205.0

### ISSUE THREAD

**Issue by anton-exe** [Artemis-chan/osu-DIVA#65]
[An attribute was renamed in 2022.205.0](https://github.com/ppy/osu/wiki/Breaking-Changes#20222050) which makes the ruleset fail to add.

**Comment by Artemis-chan** [comment]
ok I'll fix this when I get time

**Comment by anton-exe** [comment]
I made a pull request #67 which should fix it

**Comment by Artemis-chan** [comment]
ok tested the latest build version it works, but the tests are failing need to look into that (#68)
