### ISSUE TITLE
Tests can't find 'bass' library

### ISSUE THREAD

**Issue by Artemis-chan** [Artemis-chan/osu-DIVA#68]
Unit tests failing because it can't find bass library. Need to look into that.

**Comment by Thesola10** [comment]
Got a log? Bass is the library used by osu!lazer to provide audio playback and soundcard access.

**Comment by Artemis-chan** [comment]
@Thesola10 [here](https://github.com/Artemis-chan/osu-DIVA/runs/5256605472?check_suite_focus=true)
can repro in my pc, turns out it got fixed by moving to dotnet 6.0

**Comment by Artemis-chan** [comment]
should be fixed by [6317168](https://github.com/Artemis-chan/osu-DIVA/commit/631716854fdca6236edc0a71d9e1ac61d65aa0cb)

**Comment by Artemis-chan** [comment]
[seems to work fine](https://github.com/Artemis-chan/osu-DIVA/runs/5356131830?check_suite_focus=true)
