### ISSUE TITLE
Failed to add ruleset 

### ISSUE THREAD

**Issue by Origami-Lemon** [Artemis-chan/osu-DIVA#71]
!
![Screenshot (109)](https://user-images.githubusercontent.com/95983152/158277250-3e660df1-d75c-46c5-be39-0e4464292389.png)

**Comment by Artemis-chan** [comment]
duplicate of #38
I'll publish a new build

**Comment by Artemis-chan** [comment]
thanks @Thesola10

**Comment by Thesola10** [comment]
@Artemis-chan pls update the release message as you see fit

**Comment by Artemis-chan** [comment]
@Thesola10 already did 👍🏼
