### ISSUE TITLE
A Unhandled Error (osu!DIVA - 2022.314.0)

### ISSUE THREAD

**Issue by Origami-Lemon** [Artemis-chan/osu-DIVA#73]
Hello! I was Going To Play But It said A _Unhandled Error_??
Thought This Could Help 
Have a nice day! 

![image](https://user-images.githubusercontent.com/95983152/158459475-91ac837f-9565-4da7-b3f5-2f893aaa696f.png)

**Comment by Thesola10** [comment]
Make sure to use the latest version we published today as per #72 and keep us posted if the problem persists.

**Comment by Thesola10** [comment]
By the way @Artemis-chan could you add an issue template entry that encourages users to update or build from source? I think GitHub has options to make issues templates that direct users away from the issue editor

**Comment by Thesola10** [comment]
Scratch that, the error message doesn't look like a simple version mismatch, will carry out further testing on our part.

I'm having laptop issues right now, so it might take a little while.

**Comment by Artemis-chan** [comment]
it turns out because I bumped to 2022.314.1, it's being incompatible with 2022.314.0.

I've added the older version to release https://github.com/Artemis-chan/osu-DIVA/releases/download/v0.3.1/osu.Game.Rulesets.Diva_2022.314.0.dll
