### ISSUE TITLE
The future of osu!DIVA development

### ISSUE THREAD

**Issue by Thesola10** [Artemis-chan/osu-DIVA#8]
I realize that development has pretty much stalled on this project -- we all get tired of projects.

All I want in this issue is to make sure that you're okay with someone else (me?) continuing development and becoming the "primary fork", or if you would like to retain ownership of the overarching project.

You can find my continuation project over on my fork: https://github.com/Thesola10/osu-DIVA/projects/1

**Comment by Thesola10** [comment]
Fixes Thesola10#8
(also how crazy is it that both issues are #8 :3)

**Comment by Artemis-chan** [comment]
I'm not sure. I do like the next gen project you are doing and I actually want to help with the development.

**Comment by Artemis-chan** [comment]
What do you would be the best way for both of us to continue development. if you want you can have your fork become the main i wont mind or i can add you as collaborator.
But i wanna keep working on it, your project kinda motivates me.

**Comment by Thesola10** [comment]
So if I add you as a collaborator to my fork (because moving all the issues and projects over is a hassle) it would be fine to make it the main repo?

**Comment by Artemis-chan** [comment]
how about we short out the issues there then merge it to this and then continue on this. 😅 (btw its midnight I'll get to you tomorrow)

**Comment by Thesola10** [comment]
Ok, I'll see what I can do to transfer the tickets

**Comment by Artemis-chan** [comment]
i dont mean transfer them, i mean just we work on your fork till we finish the issues you got already then again return to this fork, working on this.

**Comment by Thesola10** [comment]
I think we should keep this open as long as the NextGen milestone isn't reached

**Comment by Artemis-chan** [comment]
yeah, we can transfer the long term stuff like editor tho. ill add you to collab too tomorrow  👍🏻

**Comment by Thesola10** [comment]
I think you accidentally pushed WIP fork code on master via thesola10/osu-DIVA#30

**Comment by Artemis-chan** [comment]
nah it wasn't accidental

**Comment by Artemis-chan** [comment]
ok i think i'll be updating and publishing releases in this fork from now on

**Comment by Thesola10** [comment]
:+1:
