### ISSUE TITLE
[BUG] Game not recognizing the buttons

### ISSUE THREAD

**Issue by Kissadere** [Artemis-chan/osu-DIVA#86]
The game is not recognizing the arrows, only the normal buttons (Square, Triangle, Cross and Circle). So you basically fail at once.

Also, you can't select mods.

**Comment by Artemis-chan** [comment]
I fix the mods issue. 
But I can not reproduce the buttons issue :/
It is working fine for me. pressing both face button + arrow for arrows and just the face button for the letters. 
did you try resetting the buttons?
